server:
  port: 80
  servlet:
    context-path: /EasyUIDemo

spring:
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Huang520
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl